spring.application.name=secure-auth
spring.datasource.url=jdbc:h2:mem:securedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin_user
spring.datasource.password=SecurePass@2026
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.mode=always
